#!/bin/bash
set -e

: "${POSTGRES_HOST:?Need to set POSTGRES_HOST}"
: "${POSTGRES_USER:?Need to set POSTGRES_USER}"
: "${POSTGRES_PASSWORD:?Need to set POSTGRES_PASSWORD}"

: "${POSTGRES_CIFRA_K_DB:?Need to set POSTGRES_CIFRA_K_DB}"
: "${POSTGRES_CIFRA_K_USER:?Need to set POSTGRES_CIFRA_K_USER}"
: "${POSTGRES_CIFRA_K_PASSWORD:?Need to set POSTGRES_CIFRA_K_PASSWORD}"

export PGPASSWORD=$POSTGRES_PASSWORD

echo "WAITING FOR POSTGRES..."
until pg_isready -h "$POSTGRES_HOST" -p "$POSTGRES_PORT" -U "$POSTGRES_USER"; do
  sleep 5
done

exists=$(psql -h "$POSTGRES_HOST" -U "$POSTGRES_USER" -p "$POSTGRES_PORT" -tAc "SELECT 1 FROM pg_roles WHERE rolname='$POSTGRES_CIFRA_K_USER'")
if [ "$exists" = "1" ]; then
  echo "USER \"$POSTGRES_CIFRA_K_USER\" ALREADY EXIST, UPDATE PASSWORD"
  psql -h "$POSTGRES_HOST" -U "$POSTGRES_USER" -p "$POSTGRES_PORT" -c "ALTER USER \"$POSTGRES_CIFRA_K_USER\" WITH PASSWORD '$POSTGRES_CIFRA_K_PASSWORD';"
else
  echo "CREATE USER \"$POSTGRES_CIFRA_K_USER\"..."
  psql -h "$POSTGRES_HOST" -U "$POSTGRES_USER" -p "$POSTGRES_PORT" -c "CREATE USER \"$POSTGRES_CIFRA_K_USER\" WITH PASSWORD '$POSTGRES_CIFRA_K_PASSWORD';"
fi

exists_db=$(psql -h "$POSTGRES_HOST" -U "$POSTGRES_USER" -p "$POSTGRES_PORT" -tAc "SELECT 1 FROM pg_database WHERE datname='$POSTGRES_CIFRA_K_DB'")
if [ "$exists_db" != "1" ]; then
  echo "CREATE DATABASE \"$POSTGRES_CIFRA_K_DB\"..."
  psql -h "$POSTGRES_HOST" -U "$POSTGRES_USER" -p "$POSTGRES_PORT" -c "CREATE DATABASE \"$POSTGRES_CIFRA_K_DB\" OWNER \"$POSTGRES_CIFRA_K_USER\";"
  psql -h "$POSTGRES_HOST" -U "$POSTGRES_USER" -d "$POSTGRES_CIFRA_K_DB" -p "$POSTGRES_PORT" -c "CREATE EXTENSION IF NOT EXISTS postgis;"
else
  echo "DATABASE \"$POSTGRES_CIFRA_K_DB\" ALREADY EXIST"
fi
