# Generated by Django 6.0.1 on 2026-01-21 13:58

import django.contrib.gis.db.models.fields
from django.contrib.gis.geos import Point
from django.db import migrations, models


def seed_venues(apps, schema_editor):
    Venue = apps.get_model('app', 'Venue')

    venues = [
        ("Москва", Point(37.6173, 55.7558)),
        ("Санкт-Петербург", Point(30.3141, 59.9386)),
        ("Новосибирск", Point(82.9236, 55.0302)),
        ("Екатеринбург", Point(60.5975, 56.8380)),
        ("Казань", Point(49.1221, 55.7961)),
        ("Нижний Новгород", Point(44.0086, 56.3269)),
        ("Самара", Point(50.1167, 53.1959)),
        ("Ростов-на-Дону", Point(39.7015, 47.2357)),
        ("Владивосток", Point(131.8855, 43.1198)),
        ("Сочи", Point(39.7154, 43.5853)),
    ]

    for title, location in venues:
        Venue.objects.create(title=title, location=location)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Название', max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='Гео-координаты', srid=4326)),
            ],
        ),
        migrations.RunPython(seed_venues),
    ]
