# Generated by Django 6.0.1 on 2026-01-22 09:20

import django.db.models.deletion
from django.db import migrations, models

from app.utils import fetch_venue_weather


def seed_venue_weather(apps, schema_editor):
    Venue = apps.get_model('app', 'Venue')
    VenueWeather = apps.get_model('app', 'VenueWeather')

    for venue in Venue.objects.all():
        try:
            weather_data = fetch_venue_weather(venue.location)
            VenueWeather.objects.create(venue=venue, **weather_data)
        except Exception as e:
            print(f"Ошибка при получении погоды для {venue.title}: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_create_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueWeather',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('temperature', models.FloatField(help_text='Температура в °C')),
                ('humidity', models.FloatField(help_text='Влажность в %')),
                ('pressure', models.FloatField(help_text='Атмосферное давление в мм рт. ст.')),
                ('wind_speed', models.FloatField(help_text='Скорость ветра в м/с')),
                ('wind_direction', models.CharField(help_text='Направление ветра (N, NE, E...)', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('venue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weather', to='app.venue')),
            ],
        ),
        migrations.RunPython(seed_venue_weather)
    ]
