# Generated by Django 6.0.1 on 2026-01-22 12:03
from datetime import timedelta

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import now


def seed_events(apps, schema_editor):
    Event = apps.get_model('app', 'Event')
    Venue = apps.get_model('app', 'Venue')
    User = apps.get_model('auth', 'User')

    author = User.objects.filter(is_superuser=True).first()
    venues = list(Venue.objects.all())

    events = [
        {"name": "Музыкальный фестиваль", "description": "Большой музыкальный фестиваль под открытым небом", "rating": 20, "status": "published", "venue": venues[0]},
        {"name": "Бизнес-конференция", "description": "Конференция для предпринимателей", "rating": 18, "status": "draft", "venue": venues[1]},
        {"name": "Выставка технологий", "description": "Современные IT и стартапы", "rating": 22, "status": "published", "venue": venues[2]},
        {"name": "IT Meetup", "description": "Встреча разработчиков", "rating": 17, "status": "published", "venue": venues[5]},
        {"name": "Startup Pitch Day", "description": "Презентации стартапов инвесторам", "rating": 19, "status": "draft", "venue": venues[6]},
        {"name": "Джазовый вечер", "description": "Живой джаз", "rating": 21, "status": "published", "venue": venues[8]},
        {"name": "Маркетинговый форум", "description": "Форум по digital-маркетингу", "rating": 16, "status": "draft", "venue": venues[3]},
        {"name": "Киноночь", "description": "Фильмы под открытым небом", "rating": 23, "status": "published", "venue": venues[7]},
        {"name": "Образовательный семинар", "description": "Интенсив для специалистов", "rating": 15, "status": "draft", "venue": venues[1]},
        {"name": "Фестиваль еды", "description": "Фудкорты и street food", "rating": 24, "status": "published", "venue": venues[9]},
        {"name": "Научная конференция", "description": "Последние научные исследования", "rating": 18, "status": "published", "venue": venues[5]},
        {"name": "Геймдев митап", "description": "Разработка игр", "rating": 19, "status": "draft", "venue": venues[2]},
        {"name": "Книжная ярмарка", "description": "Презентации книг и авторы", "rating": 16, "status": "published", "venue": venues[0]},
        {"name": "HR форум", "description": "Управление персоналом", "rating": 17, "status": "draft", "venue": venues[4]},
        {"name": "Музыкальный батл", "description": "Соревнование групп", "rating": 20, "status": "published", "venue": venues[8]},
        {"name": "Digital Expo", "description": "Выставка цифровых решений", "rating": 21, "status": "published", "venue": venues[3]},
        {"name": "Кулинарный мастер-класс", "description": "Готовим с шефом", "rating": 22, "status": "draft", "venue": venues[4]},
        {"name": "Фестиваль науки", "description": "Наука для всех", "rating": 23, "status": "published", "venue": venues[6]},
        {"name": "Архитектурный форум", "description": "Современная архитектура", "rating": 18, "status": "draft", "venue": venues[7]},
        {"name": "Концерт классической музыки", "description": "Оркестр и солисты", "rating": 25, "status": "published", "venue": venues[1]},
    ]

    for idx, data in enumerate(events):
        Event.objects.create(
            name=data["name"],
            description=data["description"],
            rating=data["rating"],
            status=data["status"],
            author=author,
            venue=data["venue"],
            published_at=now() - timedelta(days=idx),
            start_at=now() + timedelta(days=idx + 1),
            end_at=now() + timedelta(days=idx + 1, hours=3),
            thumbnail="events/placeholder.jpg",
        )


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_create_venue_weather'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Название', max_length=255)),
                ('thumbnail', models.ImageField(blank=True, null=True, verbose_name='Превью-изображение')),
                ('description', models.TextField(help_text='Описание')),
                ('published_at', models.DateTimeField(help_text='Дата и время публикации')),
                ('start_at', models.DateTimeField(help_text='Дата и время начала проведения')),
                ('end_at', models.DateTimeField(help_text='Дата и время завершения проведения')),
                ('rating', models.PositiveSmallIntegerField(help_text='Рейтинг', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', help_text='Статус', max_length=9)),
                ('author', models.ForeignKey(help_text='Автор', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(help_text='Место проведения', on_delete=django.db.models.deletion.PROTECT, related_name='events', to='app.venue')),
            ],
        ),
        migrations.RunPython(seed_events),
    ]
