# Generated by Django 6.0.1 on 2026-01-22 13:27

import django.db.models.deletion
from django.db import migrations, models


def seed_event_images(apps, schema_editor):
    Event = apps.get_model('app', 'Event')
    EventImage = apps.get_model('app', 'EventImage')

    events = Event.objects.all()[:10]
    images = ['image_1.jpg', 'image_2.jpg', 'image_3.jpg']

    for event in events:
        for image in images:
            EventImage.objects.create(event=event, image=image)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_create_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.event')),
            ],
        ),
        migrations.RunPython(seed_event_images)
    ]
